version: '3.7'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    restart: always
    container_name: node-exporter
    network_mode: host
    pid: host
    command: ["--web.listen-address=0.0.0.0:9100"]
